"""pricing_lookup.py — Per-category shipping + commission lookup for MeeSell price calculator.

Data source: backend/app/data/meesho_pricing_lookup.json
  Generated by: backend/scripts/build_pricing_lookup.py
  Refreshed:    monthly (W6 — folded into the existing monthly category scrape)

Reload semantics:
  The lookup is loaded once at first call via @lru_cache(maxsize=1) on _load().
  A W6 refreshed data file is picked up on the next process restart / deploy.
  No hot-reload is provided — the static file is a shipped production artifact.

Public API:
  get_shipping(meesho_leaf_id: str) -> int
  get_commission_default(meesho_leaf_id: str) -> Decimal
  lookup_size() -> int

Dependencies: stdlib + decimal only.  No SQLAlchemy, no network, no DB.
"""

from __future__ import annotations

import json
from decimal import Decimal
from functools import lru_cache
from pathlib import Path

_DATA_FILE = Path(__file__).resolve().parent.parent.parent / "data" / "meesho_pricing_lookup.json"


class UnknownCategoryError(KeyError):
    """Raised when a meesho_leaf_id (sscat_id) is not present in the pricing lookup.

    A miss is a data-integrity bug: a seeded category has no pricing row.
    Callers (W2 pricing engine / router) must translate this to a clear 4xx error.
    Never silently fall back to a default shipping value — a wrong shipping number
    silently produces a wrong settlement, which is worse than a clear error.
    """


@lru_cache(maxsize=1)
def _load() -> dict[str, dict]:
    """Load the lookup sub-dict from meesho_pricing_lookup.json.  Cached for process lifetime."""
    with _DATA_FILE.open(encoding="utf-8") as fh:
        data: dict = json.load(fh)
    return data["lookup"]


def get_shipping(meesho_leaf_id: str) -> int:
    """Per-category constant shipping charge for the given Meesho leaf id (sscat_id).

    Args:
        meesho_leaf_id: The Meesho leaf category id (= categories.meesho_leaf_id).
                        String form, e.g. "10949".  Coerced to str defensively.

    Returns:
        Shipping charge in rupees (integer, ₹48–₹8,435).

    Raises:
        UnknownCategoryError: if the id is not present in the lookup.
    """
    key = str(meesho_leaf_id)
    lookup = _load()
    if key not in lookup:
        raise UnknownCategoryError(
            f"meesho_leaf_id {key!r} not found in pricing lookup "
            f"(lookup has {len(lookup)} entries). "
            "Re-run backend/scripts/build_pricing_lookup.py after the next scraper run."
        )
    return int(lookup[key]["shipping_charges"])


def get_commission_default(meesho_leaf_id: str) -> Decimal:
    """Default commission percentage for the category (always Decimal('0') for V1).

    Commission is kept as a look-through accessor (not hardcoded to 0) so W6
    monthly refreshes are honored if Meesho ever starts charging commission.

    Args:
        meesho_leaf_id: The Meesho leaf category id.  Coerced to str defensively.

    Returns:
        Commission percentage as a Decimal (currently Decimal('0') for all categories).

    Raises:
        UnknownCategoryError: if the id is not present in the lookup.
    """
    key = str(meesho_leaf_id)
    lookup = _load()
    if key not in lookup:
        raise UnknownCategoryError(
            f"meesho_leaf_id {key!r} not found in pricing lookup "
            f"(lookup has {len(lookup)} entries)."
        )
    return Decimal(str(lookup[key]["commission_percentage"]))


def lookup_size() -> int:
    """Number of entries in the loaded lookup (for health checks and validation tests)."""
    return len(_load())
