"""adapters/msg91.py — OTP send transport wrapper (§6.C).

Thin transport wrapper over MSG91's OTP send REST endpoint.

LOCKED EXCEPTION to §6.G's raise-on-failure pattern
---------------------------------------------------
This adapter NEVER raises on transport failure.  It returns
:class:`Msg91Response` with ``success=False``, ``request_id=None``, and
a ``message`` body containing the vendor message (or transport exception
class name).  The caller — ``iam.service.send_otp_for_login`` — surfaces
the 503 to the seller per §1.E ("MSG91 → 5xx surfaced to client").

Rate limiting
-------------
The 3/h/phone soft cap (per ``MVP_ARCH §10.7``) is enforced at
``core/middleware/rate_limit_mw.py`` BEFORE the route handler.  The
adapter trusts that its caller has already gated.

OTP generation
--------------
The 6-digit OTP code is generated by ``iam`` (the module) and PASSED IN
to ``send_otp(phone, otp, ...)``.  This adapter NEVER generates an OTP.
"""

from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass

import httpx

from app.shared.config import settings

logger = logging.getLogger(__name__)


_MSG91_OTP_URL = "https://control.msg91.com/api/v5/otp"
"""MSG91's OTP send endpoint.  Reserved — vendor URL never moves into env."""

_REQUEST_TIMEOUT_S = 10.0
_MAX_RETRIES = 1
"""1 retry on transient (connection error, 5xx, 429) per §6.C."""
_RETRY_DELAY_S = 1.0


@dataclass(frozen=True)
class Msg91Response:
    """Locked envelope per §6.C.

    Attributes:
        success: True on 2xx + vendor-success body.  False otherwise.
        request_id: MSG91 correlation ID on success.  None on failure.
            Logged but NEVER surfaced to the seller-facing API response.
        message: Vendor error message on failure.  Empty on success.
    """

    success: bool
    request_id: str | None
    message: str


# ── Lazy singleton client ──────────────────────────────────────────────────
_client: httpx.AsyncClient | None = None
_init_lock: asyncio.Lock | None = None


def _get_init_lock() -> asyncio.Lock:
    global _init_lock
    if _init_lock is None:
        _init_lock = asyncio.Lock()
    return _init_lock


async def _get_client() -> httpx.AsyncClient:
    """Lazy ``httpx.AsyncClient`` — single instance per process.

    ``httpx.AsyncClient`` carries its own connection pool; we want it
    shared across calls to avoid per-request socket churn.
    """
    global _client
    if _client is not None:
        return _client
    async with _get_init_lock():
        if _client is None:
            _client = httpx.AsyncClient(timeout=_REQUEST_TIMEOUT_S)
    return _client


# ── Public API ─────────────────────────────────────────────────────────────
async def send_otp(
    phone: str,
    otp: str,
    *,
    template_id: str | None = None,
) -> Msg91Response:
    """Dispatch a pre-generated OTP via MSG91 — see §6.C.

    Args:
        phone: E.164 format, e.g. ``"+919876543210"``.  The leading ``+``
            is stripped before the MSG91 request (vendor requirement).
        otp: 6-digit numeric OTP code.  Generated by ``iam`` — NOT here.
        template_id: Override the configured ``MSG91_TEMPLATE_ID``.

    Returns:
        :class:`Msg91Response`.  ``success=False`` on any transport error,
        non-2xx response, or MSG91 explicit failure response.

    NEVER raises (locked exception to §6.G).  The OTP value itself is
    NEVER logged.
    """
    params = {
        "template_id": template_id or settings.MSG91_TEMPLATE_ID,
        "mobile": phone.lstrip("+"),
        "authkey": settings.MSG91_AUTH_KEY,
        "otp": otp,
    }
    client = await _get_client()

    last_message = "unknown failure"
    for attempt in range(_MAX_RETRIES + 1):
        try:
            resp = await client.post(_MSG91_OTP_URL, params=params)
        except (
            httpx.ConnectError,
            httpx.TimeoutException,
            httpx.NetworkError,
            httpx.RemoteProtocolError,
        ) as exc:
            last_message = f"transport: {type(exc).__name__}"
            logger.info(
                "msg91.send_otp transport error (attempt=%d): %r", attempt + 1, exc
            )
            if attempt < _MAX_RETRIES:
                await asyncio.sleep(_RETRY_DELAY_S)
                continue
            break
        except Exception as exc:
            # Defensive non-retryable transport
            logger.warning("msg91.send_otp unexpected error: %r", exc)
            return Msg91Response(
                success=False,
                request_id=None,
                message=f"unexpected: {type(exc).__name__}",
            )

        # Got a response — decide retryability
        if resp.status_code == 429 or 500 <= resp.status_code < 600:
            last_message = f"http {resp.status_code}"
            logger.info(
                "msg91.send_otp transient http %d (attempt=%d)",
                resp.status_code,
                attempt + 1,
            )
            if attempt < _MAX_RETRIES:
                await asyncio.sleep(_RETRY_DELAY_S)
                continue
            break

        # Non-retryable response: success or vendor-explicit failure
        body = _parse_body(resp)
        if resp.status_code < 400 and body.get("type") == "success":
            return Msg91Response(
                success=True,
                request_id=str(body.get("request_id") or "") or None,
                message="",
            )
        vendor_message = body.get("message") or f"http {resp.status_code}"
        return Msg91Response(
            success=False,
            request_id=None,
            message=str(vendor_message),
        )

    return Msg91Response(success=False, request_id=None, message=last_message)


def _parse_body(resp: httpx.Response) -> dict:
    """Defensive JSON parse — MSG91 occasionally returns plain text on 5xx."""
    try:
        body = resp.json()
        return body if isinstance(body, dict) else {}
    except Exception:
        return {}


# ── Test helpers ───────────────────────────────────────────────────────────
def _reset_for_testing() -> None:
    """Reset module singletons.  Called from test fixtures only."""
    global _client, _init_lock
    _client = None
    _init_lock = None
