"""v1_baseline_13_tables

Revision ID: 935e55b4852c
Revises: 
Create Date: 2026-06-05 00:05:47.872338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '935e55b4852c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # MANUAL PATCH 1: enable pgcrypto so gen_random_uuid() works on all UUID PKs.
    # Supabase self-hosted Postgres bundles pgcrypto; IF NOT EXISTS makes this idempotent.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_aliases',
    sa.Column('variant_name', sa.String(length=128), nullable=False, comment='Raw Meesho column header — may include intentional typos'),
    sa.Column('canonical_name', sa.String(length=128), nullable=False, comment='Normalised canonical field name for internal use'),
    sa.Column('source', sa.String(length=32), nullable=False, comment="'corpus' (auto-detected) | 'manual' (curated by coordinator/founder)"),
    sa.Column('for_xlsx_export', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='TRUE → used by Export Adapter to restore Meesho header verbatim'),
    sa.PrimaryKeyConstraint('variant_name')
    )
    op.create_index('idx_field_aliases_canonical', 'field_aliases', ['canonical_name'], unique=False)
    op.create_index('idx_field_aliases_for_export', 'field_aliases', ['for_xlsx_export'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('schema_hash', sa.String(length=64), nullable=False, comment='SHA-256 of canonical schema JSON for deduplication'),
    sa.Column('schema_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('compliance_shape', sa.String(length=10), server_default=sa.text("'standard'"), nullable=False, comment='standard | collapsed — selects Export Adapter compliance strategy'),
    sa.Column('parsed_from_xlsx_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('parser_version', sa.String(length=8), server_default=sa.text("'0.2'"), nullable=False, comment='meesell-xlsx-parser version that produced this template'),
    sa.CheckConstraint("compliance_shape IN ('standard', 'collapsed')", name='ck_templates_compliance_shape'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_schema_hash'), 'templates', ['schema_hash'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False, comment='E.164 format Indian mobile, e.g. +919876543210'),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.String(length=20), server_default=sa.text("'free'"), nullable=False, comment='free | pro'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_plan'), 'users', ['plan'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False, comment='BIGSERIAL — monotonic, append-only, not UUID'),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False, comment='product.patch | product.export | seller_profile.update | auth.login'),
    sa.Column('entity_type', sa.String(length=20), nullable=True, comment='product | seller_profile | user — NULL for auth.login'),
    sa.Column('entity_id', sa.UUID(), nullable=True, comment='ID of the affected entity — NULL for auth.login'),
    sa.Column('diff_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='{before: {...}, after: {...}} — canonical field names only, PII scrubbed'),
    sa.Column('metadata_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Request context: ip, user_agent, request_id, session_id'),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_user_time', 'audit_events', ['user_id', 'occurred_at'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('meesho_leaf_id', sa.String(length=16), nullable=False, comment="Meesho's own leaf node ID, e.g. '10003'"),
    sa.Column('super_id', sa.String(length=8), nullable=False, comment="Meesho super-category ID, e.g. '11' = Women Fashion"),
    sa.Column('super_name', sa.String(length=64), nullable=False, comment='Meesho super-category display name'),
    sa.Column('path', sa.Text(), nullable=False, comment='Full breadcrumb path — trigram-indexed for browse search'),
    sa.Column('leaf_name', sa.String(length=255), nullable=False, comment='Terminal category name — trigram-indexed for prefix/fuzzy search'),
    sa.Column('template_id', sa.UUID(), nullable=False, comment='Template this leaf maps to (shared among leaves with identical schemas)'),
    sa.Column('commission_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meesho_leaf_id')
    )
    op.create_index('idx_categories_meesho_leaf', 'categories', ['meesho_leaf_id'], unique=False)
    op.create_index('idx_categories_super', 'categories', ['super_id'], unique=False)
    op.create_index('idx_categories_template', 'categories', ['template_id'], unique=False)
    op.create_table('seller_profile',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User this profile belongs to (1-1 with users)'),
    sa.Column('manufacturer_name', sa.Text(), nullable=False),
    sa.Column('manufacturer_address', sa.Text(), nullable=False),
    sa.Column('manufacturer_pincode', sa.String(length=6), nullable=False, comment='6-digit Indian PIN code'),
    sa.Column('packer_name', sa.Text(), nullable=False),
    sa.Column('packer_address', sa.Text(), nullable=False),
    sa.Column('packer_pincode', sa.String(length=6), nullable=False, comment='6-digit Indian PIN code'),
    sa.Column('importer_name', sa.Text(), nullable=True),
    sa.Column('importer_address', sa.Text(), nullable=True),
    sa.Column('importer_pincode', sa.String(length=6), nullable=True, comment='6-digit Indian PIN code'),
    sa.Column('country_of_origin', sa.String(length=64), server_default=sa.text("'India'"), nullable=False),
    sa.Column('compliance_extensions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('active_super_categories', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('onboarding_complete', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='True once all compulsory base fields are filled'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_seller_profile_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('idx_seller_profile_super_cats', 'seller_profile', ['active_super_categories'], unique=False, postgresql_using='gin')
    op.create_table('catalogs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Tenant owner'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'draft'"), nullable=False, comment='draft | submitted | exported'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_catalogs_category_id', 'catalogs', ['category_id'], unique=False)
    op.create_index('idx_catalogs_user', 'catalogs', ['user_id'], unique=False)
    op.create_index('idx_catalogs_user_created', 'catalogs', ['user_id', 'created_at'], unique=False)
    op.create_table('field_enum_values',
    sa.Column('category_id', sa.UUID(), nullable=False, comment='FK to categories — enum values are per-category'),
    sa.Column('field_name', sa.String(length=128), nullable=False, comment='Canonical field name (normalised via field_aliases)'),
    sa.Column('enum_entries', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Richer enum structure per §5.6.4'),
    sa.Column('value_count', sa.Integer(), nullable=False, comment='len(enum_entries) — materialised for query speed'),
    sa.Column('truncated', sa.Boolean(), server_default='false', nullable=False, comment='TRUE if stored enum_entries are a sample of a larger set'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_field_enum_values_category_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id', 'field_name')
    )
    op.create_index('idx_field_enum_value_count', 'field_enum_values', ['value_count'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('catalog_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Tenant owner — every query MUST filter by this column'),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fields_jsonb', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('ai_suggestions_jsonb', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'draft'"), nullable=False, comment='draft | ready | exported | deleted'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='Non-NULL → soft-deleted; excluded from active product queries'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_products_catalog_id', 'products', ['catalog_id'], unique=False)
    op.create_index('idx_products_category', 'products', ['category_id'], unique=False)
    op.create_index('idx_products_status', 'products', ['status'], unique=False)
    op.create_index('idx_products_user', 'products', ['user_id'], unique=False)
    op.create_index('idx_products_user_status', 'products', ['user_id', 'status'], unique=False)
    op.create_table('exports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Tenant owner — explicit FK for direct tenant-scoped queries'),
    sa.Column('xlsx_gcs_path', sa.Text(), nullable=True, comment='GCS object path for the generated XLSX file'),
    sa.Column('zip_gcs_path', sa.Text(), nullable=True, comment='GCS object path for the images ZIP file'),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'processing'"), nullable=False, comment='processing | ready | failed'),
    sa.Column('download_url', sa.Text(), nullable=True, comment='Signed GCS URL for download (TTL 1h) — set once status=ready'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Set when status=failed; may be seller-facing or internal'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exports_product_id', 'exports', ['product_id'], unique=False)
    op.create_index('idx_exports_user_id', 'exports', ['user_id'], unique=False)
    op.create_table('pricing_calcs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=True, comment='Maximum Retail Price entered by seller'),
    sa.Column('meesho_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='Listing price on Meesho (seller-facing price)'),
    sa.Column('seller_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='Amount Meesho remits to seller after commission deduction'),
    sa.Column('commission_pct', sa.Numeric(precision=5, scale=2), nullable=True, comment="Meesho commission rate for the product's category"),
    sa.Column('gst_pct', sa.Numeric(precision=5, scale=2), nullable=True, comment='GST rate applicable to the product'),
    sa.Column('margin', sa.Numeric(precision=10, scale=2), nullable=True, comment='Absolute margin (seller_price - cost of goods) in INR'),
    sa.Column('margin_pct', sa.Numeric(precision=5, scale=2), nullable=True, comment='Margin as percentage of seller_price'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pricing_calcs_product_id', 'pricing_calcs', ['product_id'], unique=False)
    op.create_table('product_drafts',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Tenant owner (part of composite PK)'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='Product this draft belongs to (part of composite PK)'),
    sa.Column('draft_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Full wizard field state for crash recovery — upserted on every PATCH'),
    sa.Column('saved_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='Timestamp of last upsert'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_product_drafts_product_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_product_drafts_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'product_id')
    )
    op.create_index('idx_product_drafts_product_id', 'product_drafts', ['product_id'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('gcs_path', sa.Text(), nullable=False, comment='GCS object path: {user_id}/{product_id}/{order_idx}.jpg'),
    sa.Column('order_idx', sa.Integer(), nullable=False, comment='1 (front/compulsory) to 4 (optional) — CHECK 1..4 enforced'),
    sa.Column('is_front', sa.Boolean(), sa.Computed('order_idx = 1', persisted=True), nullable=False, comment='GENERATED ALWAYS AS (order_idx = 1) STORED'),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('color_space', sa.String(length=8), nullable=True, comment='RGB | CMYK | L (greyscale)'),
    sa.Column('precheck_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False, comment='pending | processing | ready | failed'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('order_idx BETWEEN 1 AND 4', name='ck_product_images_order_idx'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'order_idx', name='uq_product_images_product_order')
    )
    op.create_index('idx_product_images_product_id', 'product_images', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_product_images_product_id', table_name='product_images')
    op.drop_table('product_images')
    op.drop_index('idx_product_drafts_product_id', table_name='product_drafts')
    op.drop_table('product_drafts')
    op.drop_index('idx_pricing_calcs_product_id', table_name='pricing_calcs')
    op.drop_table('pricing_calcs')
    op.drop_index('idx_exports_user_id', table_name='exports')
    op.drop_index('idx_exports_product_id', table_name='exports')
    op.drop_table('exports')
    op.drop_index('idx_products_user_status', table_name='products')
    op.drop_index('idx_products_user', table_name='products')
    op.drop_index('idx_products_status', table_name='products')
    op.drop_index('idx_products_category', table_name='products')
    op.drop_index('idx_products_catalog_id', table_name='products')
    op.drop_table('products')
    op.drop_index('idx_field_enum_value_count', table_name='field_enum_values')
    op.drop_table('field_enum_values')
    op.drop_index('idx_catalogs_user_created', table_name='catalogs')
    op.drop_index('idx_catalogs_user', table_name='catalogs')
    op.drop_index('idx_catalogs_category_id', table_name='catalogs')
    op.drop_table('catalogs')
    # MANUAL PATCH 2: drop_index does not accept postgresql_using kwarg; removed.
    op.drop_index('idx_seller_profile_super_cats', table_name='seller_profile')
    op.drop_table('seller_profile')
    op.drop_index('idx_categories_template', table_name='categories')
    op.drop_index('idx_categories_super', table_name='categories')
    op.drop_index('idx_categories_meesho_leaf', table_name='categories')
    op.drop_table('categories')
    op.drop_index('idx_audit_user_time', table_name='audit_events')
    op.drop_index('idx_audit_entity', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_plan'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_templates_schema_hash'), table_name='templates')
    op.drop_table('templates')
    op.drop_index('idx_field_aliases_for_export', table_name='field_aliases')
    op.drop_index('idx_field_aliases_canonical', table_name='field_aliases')
    op.drop_table('field_aliases')
    # ### end Alembic commands ###
