import { useState } from "react";

const METHODS = [
  {
    id: "csv-bridge",
    name: "CSV Upload/Download Bridge",
    phase: "MVP (Month 1-3)",
    phaseColor: "#57cc99",
    difficulty: "Easy",
    reliability: "HIGH",
    risk: "NONE",
    icon: "📄",
    how: "Seller manually downloads CSVs from Meesho Supplier Panel (orders, settlements, TCS data) → uploads to MeeSell for analysis. MeeSell generates Meesho-formatted catalog CSVs → seller uploads to Meesho manually.",
    inbound: [
      "Order report CSV (from Meesho panel → Orders → Download)",
      "Settlement/payment CSV (from Meesho panel → Payments → Download)",
      "TCS export CSV (for GST reconciliation)",
      "Return report CSV",
    ],
    outbound: [
      "Meesho bulk catalog CSV (generated by CatalogAI, seller uploads to Meesho)",
      "Product images (1024×1024, white BG, saved to device → manual upload)",
    ],
    pros: [
      "Zero ToS violation risk — seller owns their own data",
      "No Meesho approval needed",
      "Works immediately, no API dependency",
      "Same approach VariantStudio uses for Tally XML",
      "Same approach Meesho Supplier Analytics Chrome extension uses",
    ],
    cons: [
      "Manual — seller must download/upload CSVs",
      "Not real-time — batch processing",
      "Extra steps in workflow (friction)",
      "No auto-sync of inventory or orders",
    ],
    whoUsesThis: "VariantStudio, Meesho Supplier Analytics extension, ReconPe, all free calculator tools",
  },
  {
    id: "chrome-ext",
    name: "Chrome Extension (Panel Augmentation)",
    phase: "Phase 2 (Month 4-6)",
    phaseColor: "#48bfe3",
    difficulty: "Medium",
    reliability: "HIGH",
    risk: "LOW",
    icon: "🧩",
    how: "Build a Chrome extension that activates when seller opens supplier.meesho.com. Extension reads DOM data (order counts, catalog info, settlement data) and sends it to MeeSell backend. Can also inject UI elements (quality scores, pricing alerts) directly into the Meesho panel.",
    inbound: [
      "Read order data from Meesho panel DOM in real-time",
      "Extract settlement amounts, return counts, catalog performance",
      "Capture catalog listing details (titles, images, categories)",
      "Read notification/alert data from panel",
    ],
    outbound: [
      "Inject quality score badge next to each catalog listing",
      "Show profit/loss indicator per order in orders tab",
      "Add 'Optimize with MeeSell' button to catalog section",
      "Auto-fill catalog form fields with AI-generated content",
    ],
    pros: [
      "Near real-time data without API — reads what seller already sees",
      "Can INJECT features INTO Meesho panel (huge UX win)",
      "Seller doesn't need to switch between tools",
      "Chrome extensions are normal — many ecom tools use this approach",
      "Data stays in seller's browser session (privacy advantage)",
    ],
    cons: [
      "Only works on desktop Chrome (not mobile / Meesho app)",
      "DOM structure can change when Meesho updates their panel",
      "Requires maintenance when Meesho UI changes",
      "Review/approval process for Chrome Web Store",
    ],
    whoUsesThis: "Meesho Supplier Analytics extension, Helium 10 (for Amazon), Jungle Scout, SellerApp — all use Chrome extensions to augment marketplace panels",
  },
  {
    id: "session-cookie",
    name: "Session Cookie Authentication",
    phase: "Phase 2-3 (Month 4-9)",
    phaseColor: "#ffd166",
    difficulty: "Medium",
    reliability: "MEDIUM",
    risk: "MEDIUM",
    icon: "🍪",
    how: "Seller pastes their Meesho session cookie into MeeSell. MeeSell uses this to make authenticated requests to Meesho's internal APIs on behalf of the seller — pulling order data, catalog info, settlement details programmatically.",
    inbound: [
      "Pull full order history via Meesho's internal API endpoints",
      "Fetch catalog performance data (views, clicks, conversion)",
      "Download settlement reports programmatically",
      "Get real-time inventory levels",
    ],
    outbound: [
      "Potentially auto-upload catalogs (risky — see cons)",
      "Update pricing programmatically",
      "Modify inventory levels",
    ],
    pros: [
      "Closest to a real API without having API access",
      "Can pull data automatically — no manual CSV downloads",
      "VariantStudio already does this successfully",
      "Seller explicitly consents by pasting their cookie",
    ],
    cons: [
      "Session cookies expire (every few hours/days) — needs re-pasting",
      "Meesho could block/rate-limit non-browser requests",
      "Potential ToS gray area — using internal APIs",
      "If Meesho changes internal API endpoints, breaks integration",
      "Security responsibility — storing seller's session tokens",
    ],
    whoUsesThis: "VariantStudio (explicitly asks 'Paste your Meesho session cookie. Takes 30 seconds.')",
  },
  {
    id: "official-api",
    name: "Official Meesho Supplier API (Partner)",
    phase: "Phase 3+ (Month 9+)",
    phaseColor: "#7b68ee",
    difficulty: "Hard (political, not technical)",
    reliability: "HIGHEST",
    risk: "NONE",
    icon: "🔑",
    how: "Apply to become an official Meesho technology partner. Meesho provides API credentials (Client-ID, Secret-Key, Supplier Identifier). Get access to Order Management API, Catalog API, Inventory Sync, Label Fetch, etc.",
    inbound: [
      "Full order lifecycle (pending → shipped → delivered → RTO)",
      "Catalog item sync and mapping",
      "Real-time inventory levels",
      "Settlement and payment data",
      "Return and cancellation webhooks",
    ],
    outbound: [
      "Upload catalogs via API",
      "Update inventory in real-time",
      "Confirm/pack orders",
      "Fetch shipping labels",
    ],
    pros: [
      "The gold standard — full, sanctioned, stable access",
      "Real-time webhooks for orders and returns",
      "Unicommerce, EasyEcom, Fynd, Eshopbox all use this",
      "No ToS risk, no breakage risk",
      "Enables full automation end-to-end",
    ],
    cons: [
      "Requires Meesho's approval — they gate this for enterprise partners",
      "May require minimum seller volume or commercial agreement",
      "Onboarding process takes weeks/months",
      "Need to prove product value before Meesho opens access",
      "Not available to small startups at Day 1",
    ],
    whoUsesThis: "Unicommerce, EasyEcom, Vinculum, Fynd/Konnect, Eshopbox — all are established enterprise partners",
  },
  {
    id: "scraping",
    name: "Public Data Scraping (Competitor Intel)",
    phase: "Phase 2 (Month 4-6)",
    phaseColor: "#e07a5f",
    difficulty: "Medium",
    reliability: "MEDIUM",
    risk: "LOW-MEDIUM",
    icon: "🕷️",
    how: "Scrape public Meesho product pages for competitor pricing, product data, category trends. This is PUBLIC data (not seller panel) — anyone can see it by browsing meesho.com.",
    inbound: [
      "Competitor product prices in same category",
      "Product ratings and review counts",
      "Category trending products",
      "Seller names and catalog counts",
    ],
    outbound: ["N/A — read-only intelligence gathering"],
    pros: [
      "Public data — lower legal risk than internal API scraping",
      "Powers PriceIntel competitive monitoring feature",
      "Apify, RealDataAPI already sell Meesho scrapers",
      "Can be done with Playwright + rotating proxies",
    ],
    cons: [
      "Meesho can block/rate-limit scrapers",
      "Need proxy rotation infrastructure",
      "Data freshness depends on scraping frequency",
      "At scale, can get expensive (proxy costs)",
    ],
    whoUsesThis: "Product Data Scrape, RealDataAPI, RetailGators, Apify (all sell Meesho scrapers commercially)",
  },
];

const diffColor = { Easy: "#57cc99", Medium: "#ffd166", "Hard (political, not technical)": "#e07a5f" };
const reliColor = { HIGHEST: "#57cc99", HIGH: "#48bfe3", MEDIUM: "#ffd166" };
const riskColor = { NONE: "#57cc99", LOW: "#48bfe3", "LOW-MEDIUM": "#ffd166", MEDIUM: "#e07a5f" };

export default function MeeshoIntegration() {
  const [expanded, setExpanded] = useState(new Set(["csv-bridge"]));
  const toggle = id => setExpanded(p => { const n = new Set(p); n.has(id) ? n.delete(id) : n.add(id); return n; });

  return (
    <div style={{ minHeight: "100vh", background: "#0a0a0f", color: "#e0e0e0", fontFamily: "'DM Sans', sans-serif", padding: "28px 20px 50px" }}>
      <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500;700&family=Instrument+Serif&display=swap" rel="stylesheet" />

      <div style={{ maxWidth: 1020, margin: "0 auto 20px" }}>
        <div style={{ fontSize: 10, letterSpacing: "0.15em", color: "#e07a5f", textTransform: "uppercase", fontWeight: 600, marginBottom: 6 }}>
          Critical Architecture Decision
        </div>
        <h1 style={{ fontFamily: "'Instrument Serif', serif", fontSize: 28, fontWeight: 400, margin: "0 0 6px", color: "#fff" }}>
          How does MeeSell connect to Meesho?
        </h1>
        <p style={{ color: "#777", fontSize: 13, margin: 0, lineHeight: 1.5 }}>
          The honest answer: Meesho has NO open public API. Here are the 5 real integration paths, their tradeoffs, and how to phase them.
        </p>
      </div>

      {/* Reality check box */}
      <div style={{ maxWidth: 1020, margin: "0 auto 20px", background: "#ff444410", border: "1px solid #ff444422", borderRadius: 12, padding: "16px 20px" }}>
        <div style={{ fontSize: 11, fontWeight: 700, color: "#ff6b6b", letterSpacing: "0.06em", textTransform: "uppercase", marginBottom: 8 }}>
          ⚠️ Reality Check — Meesho's API Landscape
        </div>
        <div style={{ fontSize: 13, color: "#ccc", lineHeight: 1.7 }}>
          <strong style={{ color: "#eee" }}>Meesho does have a Supplier API</strong> — but it's <strong style={{ color: "#ff6b6b" }}>partner-gated</strong>. Only approved enterprise partners (Unicommerce, EasyEcom, Fynd) get credentials (Client-ID + Secret-Key + Supplier Identifier). A Day-1 startup won't get this access. 
          Every successful Meesho-specific tool in the market today started with one of the workaround methods below, then graduated to official API access after proving value.
        </div>
      </div>

      {/* Phased strategy */}
      <div style={{ maxWidth: 1020, margin: "0 auto 18px", background: "#57cc9908", border: "1px solid #57cc9922", borderRadius: 12, padding: "16px 20px" }}>
        <div style={{ fontSize: 11, fontWeight: 700, color: "#57cc99", letterSpacing: "0.06em", textTransform: "uppercase", marginBottom: 10 }}>
          📋 Recommended Phased Strategy
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 12 }}>
          {[
            { phase: "MVP", method: "CSV Bridge", desc: "Seller downloads from Meesho, uploads to MeeSell. MeeSell generates Meesho-format CSV catalogs. Zero API dependency.", color: "#57cc99" },
            { phase: "Phase 2", method: "Chrome Extension", desc: "Extension reads Meesho panel data in real-time. Injects quality scores and pricing alerts INTO the supplier panel.", color: "#48bfe3" },
            { phase: "Phase 2-3", method: "Session Cookie + Scraping", desc: "Auto-pull seller data via session cookie. Scrape public Meesho for competitor prices. Like VariantStudio does.", color: "#ffd166" },
            { phase: "Phase 3+", method: "Official API Partner", desc: "Apply to Meesho with 2,000+ active sellers as proof. Get sanctioned API credentials for full automation.", color: "#7b68ee" },
          ].map((p, i) => (
            <div key={i} style={{ background: "rgba(255,255,255,0.02)", border: `1px solid ${p.color}22`, borderRadius: 10, padding: "12px" }}>
              <div style={{ fontSize: 9, fontWeight: 700, color: p.color, letterSpacing: "0.08em", marginBottom: 4 }}>{p.phase}</div>
              <div style={{ fontSize: 13, fontWeight: 700, color: "#ddd", marginBottom: 6 }}>{p.method}</div>
              <div style={{ fontSize: 11, color: "#888", lineHeight: 1.5 }}>{p.desc}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Data flow diagram */}
      <div style={{ maxWidth: 1020, margin: "0 auto 18px", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: 12, padding: "20px" }}>
        <div style={{ fontSize: 11, fontWeight: 700, color: "#48bfe3", letterSpacing: "0.06em", textTransform: "uppercase", marginBottom: 14 }}>
          MVP Data Flow (No API Required)
        </div>
        <div style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 8, flexWrap: "wrap" }}>
          {[
            { text: "Seller takes\nproduct photos", bg: "#ffd16615", border: "#ffd16633", color: "#ffd166" },
            { text: "→", bg: "transparent", border: "transparent", color: "#444", isArrow: true },
            { text: "Uploads to\nMeeSell", bg: "#57cc9915", border: "#57cc9933", color: "#57cc99" },
            { text: "→", bg: "transparent", border: "transparent", color: "#444", isArrow: true },
            { text: "AI generates\ntitles + images\n+ validates", bg: "#48bfe315", border: "#48bfe333", color: "#48bfe3" },
            { text: "→", bg: "transparent", border: "transparent", color: "#444", isArrow: true },
            { text: "Downloads\nMeesho CSV\n+ images", bg: "#7b68ee15", border: "#7b68ee33", color: "#7b68ee" },
            { text: "→", bg: "transparent", border: "transparent", color: "#444", isArrow: true },
            { text: "Uploads CSV to\nMeesho Supplier\nPanel manually", bg: "#e07a5f15", border: "#e07a5f33", color: "#e07a5f" },
          ].map((s, i) => s.isArrow ? (
            <span key={i} style={{ fontSize: 20, color: s.color }}>→</span>
          ) : (
            <div key={i} style={{
              background: s.bg, border: `1px solid ${s.border}`, borderRadius: 8,
              padding: "10px 14px", textAlign: "center", fontSize: 11, color: s.color,
              fontWeight: 600, lineHeight: 1.4, whiteSpace: "pre-line", minWidth: 100,
            }}>{s.text}</div>
          ))}
        </div>
        <div style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 8, flexWrap: "wrap", marginTop: 14 }}>
          {[
            { text: "Seller downloads\nsettlement CSV\nfrom Meesho", bg: "#e07a5f15", border: "#e07a5f33", color: "#e07a5f" },
            { text: "→", bg: "transparent", border: "transparent", color: "#444", isArrow: true },
            { text: "Uploads to\nMeeSell", bg: "#57cc9915", border: "#57cc9933", color: "#57cc99" },
            { text: "→", bg: "transparent", border: "transparent", color: "#444", isArrow: true },
            { text: "MeeSell parses\norders, returns,\ndeductions", bg: "#48bfe315", border: "#48bfe333", color: "#48bfe3" },
            { text: "→", bg: "transparent", border: "transparent", color: "#444", isArrow: true },
            { text: "Per-SKU P&L\n+ Return analytics\n+ Tally export", bg: "#7b68ee15", border: "#7b68ee33", color: "#7b68ee" },
          ].map((s, i) => s.isArrow ? (
            <span key={i} style={{ fontSize: 20, color: s.color }}>→</span>
          ) : (
            <div key={i} style={{
              background: s.bg, border: `1px solid ${s.border}`, borderRadius: 8,
              padding: "10px 14px", textAlign: "center", fontSize: 11, color: s.color,
              fontWeight: 600, lineHeight: 1.4, whiteSpace: "pre-line", minWidth: 100,
            }}>{s.text}</div>
          ))}
        </div>
      </div>

      {/* Detailed methods */}
      <div style={{ maxWidth: 1020, margin: "0 auto", display: "flex", flexDirection: "column", gap: 8 }}>
        {METHODS.map(m => {
          const open = expanded.has(m.id);
          return (
            <div key={m.id} style={{
              background: open ? "rgba(255,255,255,0.03)" : "rgba(255,255,255,0.015)",
              border: `1px solid ${open ? m.phaseColor + "33" : "rgba(255,255,255,0.05)"}`,
              borderRadius: 12, overflow: "hidden"
            }}>
              <div onClick={() => toggle(m.id)} style={{ padding: "14px 18px", cursor: "pointer", display: "flex", alignItems: "center", gap: 12 }}>
                <span style={{ fontSize: 22 }}>{m.icon}</span>
                <div style={{ flex: 1 }}>
                  <div style={{ fontSize: 14, fontWeight: 600, color: "#ddd" }}>{m.name}</div>
                  <div style={{ fontSize: 11, color: m.phaseColor, fontWeight: 600 }}>{m.phase}</div>
                </div>
                <div style={{ display: "flex", gap: 8 }}>
                  <span style={{ fontSize: 9, padding: "3px 6px", borderRadius: 4, background: (reliColor[m.reliability] || "#888") + "15", color: reliColor[m.reliability] || "#888", fontWeight: 700, fontFamily: "'JetBrains Mono', monospace" }}>
                    RELIABILITY: {m.reliability}
                  </span>
                  <span style={{ fontSize: 9, padding: "3px 6px", borderRadius: 4, background: (riskColor[m.risk] || "#888") + "15", color: riskColor[m.risk] || "#888", fontWeight: 700, fontFamily: "'JetBrains Mono', monospace" }}>
                    RISK: {m.risk}
                  </span>
                </div>
                <span style={{ fontSize: 16, color: "#555", transition: "transform 0.3s", transform: open ? "rotate(180deg)" : "rotate(0)" }}>▾</span>
              </div>

              {open && (
                <div style={{ padding: "0 18px 18px", borderTop: "1px solid rgba(255,255,255,0.04)" }}>
                  <p style={{ fontSize: 13, color: "#aaa", lineHeight: 1.6, margin: "12px 0 14px" }}>{m.how}</p>

                  <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, marginBottom: 14 }}>
                    <div>
                      <div style={{ fontSize: 10, fontWeight: 700, color: "#48bfe3", letterSpacing: "0.06em", textTransform: "uppercase", marginBottom: 6 }}>Data IN (Meesho → MeeSell)</div>
                      {m.inbound.map((d, i) => (
                        <div key={i} style={{ fontSize: 12, color: "#bbb", marginBottom: 3, display: "flex", gap: 6, lineHeight: 1.4 }}>
                          <span style={{ color: "#48bfe3" }}>←</span> {d}
                        </div>
                      ))}
                    </div>
                    <div>
                      <div style={{ fontSize: 10, fontWeight: 700, color: "#57cc99", letterSpacing: "0.06em", textTransform: "uppercase", marginBottom: 6 }}>Data OUT (MeeSell → Meesho)</div>
                      {m.outbound.map((d, i) => (
                        <div key={i} style={{ fontSize: 12, color: "#bbb", marginBottom: 3, display: "flex", gap: 6, lineHeight: 1.4 }}>
                          <span style={{ color: "#57cc99" }}>→</span> {d}
                        </div>
                      ))}
                    </div>
                  </div>

                  <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, marginBottom: 14 }}>
                    <div>
                      <div style={{ fontSize: 10, fontWeight: 700, color: "#57cc99", letterSpacing: "0.06em", textTransform: "uppercase", marginBottom: 6 }}>Pros</div>
                      {m.pros.map((p, i) => (
                        <div key={i} style={{ fontSize: 11.5, color: "#aaa", marginBottom: 3, display: "flex", gap: 6, lineHeight: 1.4 }}>
                          <span style={{ color: "#57cc99" }}>+</span> {p}
                        </div>
                      ))}
                    </div>
                    <div>
                      <div style={{ fontSize: 10, fontWeight: 700, color: "#e07a5f", letterSpacing: "0.06em", textTransform: "uppercase", marginBottom: 6 }}>Cons</div>
                      {m.cons.map((c, i) => (
                        <div key={i} style={{ fontSize: 11.5, color: "#aaa", marginBottom: 3, display: "flex", gap: 6, lineHeight: 1.4 }}>
                          <span style={{ color: "#e07a5f" }}>−</span> {c}
                        </div>
                      ))}
                    </div>
                  </div>

                  <div style={{ fontSize: 11, color: "#777", fontFamily: "'JetBrains Mono', monospace" }}>
                    WHO ALREADY DOES THIS → {m.whoUsesThis}
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Bottom line */}
      <div style={{ maxWidth: 1020, margin: "24px auto 0", background: "linear-gradient(135deg, #57cc9908, #7b68ee08)", border: "1px solid #57cc9922", borderRadius: 12, padding: "20px 24px" }}>
        <div style={{ fontSize: 11, fontWeight: 700, color: "#57cc99", letterSpacing: "0.08em", textTransform: "uppercase", marginBottom: 10 }}>
          🎯 The Playbook
        </div>
        <div style={{ fontSize: 14, color: "#ddd", lineHeight: 1.8 }}>
          <strong style={{ color: "#57cc99" }}>MVP = No API needed.</strong> MeeSell generates Meesho-ready catalog files (CSV + images). Seller downloads and uploads to Meesho manually. For analytics, seller uploads settlement CSVs from Meesho. This is exactly how VariantStudio works today and they're growing.
          <br /><br />
          <strong style={{ color: "#48bfe3" }}>Phase 2 = Chrome Extension.</strong> This is the unlock — the extension reads the supplier panel in real-time, injects MeeSell features directly into Meesho's UI, and eliminates the manual CSV dance. Helium 10 built a $100M+ business with this exact approach on Amazon.
          <br /><br />
          <strong style={{ color: "#7b68ee" }}>Phase 3 = Official API.</strong> Once you have 2,000+ active sellers, you approach Meesho with proof of value. At that point, you're not asking for API access — they'll want to partner with you because you're improving their supplier ecosystem.
        </div>
      </div>
    </div>
  );
}
